version: '3'

services:
  db:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - webserver

  phpmyadmin:
    container_name: pma
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - webserver

  webserver:
    container_name: web
    build: .
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
    networks:
      - webserver

networks:
  webserver:
    driver: bridge
